version: '3'
services:
  fb-sync:
    build:
      context: ./../fb-sync
      dockerfile: Dockerfile
    container_name: fb-sync
    restart: always
    depends_on:
      - redis  
    environment:
      - PORT=7000
      - DB_TYPE=mysql
      - DB_HOST=91.99.31.157
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=HoangChuong@1111
      - DB_DATABASE=crawl-fb
      - NODE_OPTIONS=--max-old-space-size=4096  
      # redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TYPE=single
    ports:
      - '7000:7000'
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: